name = "connectgbb"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".open-next"

[vars]
SUPABASE_URL = "https://srrasrbsqajtssqlxoju.supabase.co"
NEXT_PUBLIC_SUPABASE_URL = "https://srrasrbsqajtssqlxoju.supabase.co"
NPM_FLAGS = "--legacy-peer-deps"

[env.production.vars]
SUPABASE_URL = "https://srrasrbsqajtssqlxoju.supabase.co"
NEXT_PUBLIC_SUPABASE_URL = "https://srrasrbsqajtssqlxoju.supabase.co"
NPM_FLAGS = "--legacy-peer-deps"

[env.preview.vars]
SUPABASE_URL = "https://srrasrbsqajtssqlxoju.supabase.co"
NEXT_PUBLIC_SUPABASE_URL = "https://srrasrbsqajtssqlxoju.supabase.co"
NPM_FLAGS = "--legacy-peer-deps"
